### ISSUE TITLE
Not Clicking Confirmation Button

### ISSUE THREAD

**Issue by atharakhan** [mrishab/google-photos-delete-tool#5] opened 2019-07-08 23:33 UTC
Thank you for this wonderful tool.  For whatever reason, the script does not seem to click the confirmation button.  I looked at the issue opened by MickPBduece but was not able to see a solution in his notes.

**Comment by abarberis** [comment] 2019-07-10 11:47
@atharakhan I submitted a pull request a few days ago to fix it. Use that version for now. Enjoy!

**Comment by zzhang39** [comment] 2019-07-15 14:54
update confirmation button to below

confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf > button.VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.kHssdc.HvOprf'

**Comment by leewinbush** [comment] 2019-07-19 20:01
Perfect, thanks!  Looks like it's working now.

**Comment by rwat1** [comment] 2019-08-19 16:55
@zzhang39  This worked!   Thank you very much. Yes, that's working now.

**Comment by joelrose2** [comment] 2019-09-22 05:26
Thanks for this great script. It worked for me (even if slowly), but I had to do two things differently: (1) The script did not click the confirm button (“Move to Trash”) so it initially did nothing - I fixed this by replacing the button’s selector in the code manually, by copying its selector from the page as it appeared in my browser. (2) After pasting the code into console I had to press Enter to get it to start (this is not mentioned in the instructions).

**Comment by GrandNegus68** [comment] 2019-09-25 19:47
In case anyone doesn't see my reply to MickPBduece's Issue :-

It obviously looks like the button class is dynamic (my button class was different to yours and a few others here - not sure if this is client specific or code release specific). So my solution which I hope works as intended as we can't trust the class name being fixed is to use the nth-child approach so it always targets the second button, please test yourself - I am hoping it won't break if their isn't a second child in the dialogue box at any point.  anyway...

Change :- 
confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf > button.VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.DuMIQc.kHssdc.HvOprf'

To :- 
confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf button:nth-child(2)'

Thanks for the script, it is annoying that it can't be done in bulk, but this script will save me a very long time doing it manually

Further to my original reply I have been using this all day and just a gotca, it appears that anything deleted also has to be removed from the drive bin as well as photos bin.. not sure if that's just me, I read something about photos being removed from drive so in my case it might be historical, but currently even after deleting tons of photos my storage useage hasn't gone down much

**Comment by mrishab** [comment] 2019-11-14 08:45
confirmationButton fix is merged: https://github.com/mrishab/google-photos-delete-tool/pull/4

**Closed** 2019-11-14 08:46 UTC
