### ISSUE TITLE
Confirmation button not getting pushed

### ISSUE THREAD

**Issue by MickPBduece** [mrishab/google-photos-delete-tool#3] opened 2019-06-23 22:41 UTC
Hi- First let me say thank you for building a tool that solves a big problem for me.  I understand that providing this tool can be a bit or a lot of work for you.   I used the tool a few days ago and now today when I try it doesn't click the "Remove from Google Account, Google Drive, synced devices and places where it's shared?" button and when the script is running the title of the box that is display sayd "unused".  I think this is property span.Vfpkd-vQzf8d and maybe a new one since it seems I had shared this photo.

**Comment by MickPBduece** [comment] 2019-06-23 23:10
After some further examination I discerned enough to see that when the photos are shared the config is changed from 
VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.DuMIQc.kHssdc.HvOprf
to
VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ nCP5yc kHssdc HvOprf
I am a little out of my element here but maybe there is a place to put a note about this other than an "Issue".  
Thank you

**Comment by GrandNegus68** [comment] 2019-09-25 09:51
Hi There, I think the button class is dynamic which is why the confirmation button is not being clicked.. here is my solution, hope it works as intended

Change :- 
confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf > button.VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.DuMIQc.kHssdc.HvOprf'

To :- 
confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf button:nth-child(2)'

Thanks for the script, it is annoying that it can't be done in bulk, but this script will save me a very long time doing it manually

**Comment by mrishab** [comment] 2019-11-14 08:46
Fix for confirmationButton is merged: https://github.com/mrishab/google-photos-delete-tool/pull/4

**Closed by mrishab** 2019-11-14 08:46 UTC

**Comment by MickPBduece** [comment] 2019-11-18 14:06
Thanks - Appreciated
